# OpenAPI Specification for Todo Chatbot Backend

openapi: 3.0.3
info:
  title: Todo Chatbot Backend API
  description: API for managing tasks in the AI-powered todo chatbot
  version: 1.0.0
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-chatbot.com
    description: Production server

paths:
  /api/tasks:
    get:
      summary: List tasks
      description: Retrieve a list of tasks with optional filtering
      parameters:
        - name: status
          in: query
          description: Filter by task status
          required: false
          schema:
            type: string
            enum: [active, completed, archived]
        - name: priority
          in: query
          description: Filter by priority
          required: false
          schema:
            type: string
            enum: [low, medium, high]
        - name: due_date_from
          in: query
          description: Filter tasks due on or after this date
          required: false
          schema:
            type: string
            format: date
        - name: due_date_to
          in: query
          description: Filter tasks due on or before this date
          required: false
          schema:
            type: string
            format: date
        - name: tags
          in: query
          description: Filter by tags (comma separated)
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Pagination offset
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer

    post:
      summary: Create a task
      description: Create a new task with the provided details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/tasks/{id}:
    get:
      summary: Get a task
      description: Retrieve a specific task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a task
      description: Update an existing task with the provided details
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a task
      description: Delete a specific task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'

  /api/tasks/{id}/complete:
    post:
      summary: Mark task as complete
      description: Mark a task as completed
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task marked as completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/tags:
    get:
      summary: List tags
      description: Retrieve a list of tags
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'

    post:
      summary: Create a tag
      description: Create a new tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
      responses:
        '201':
          description: Tag created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/search:
    get:
      summary: Search tasks
      description: Search tasks by title, description, or tags
      parameters:
        - name: q
          in: query
          required: true
          description: Search query
          schema:
            type: string
        - name: limit
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Pagination offset
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer

  /api/events:
    post:
      summary: Publish event
      description: Publish an event to the event stream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '202':
          description: Event accepted for processing
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 200
          description: Task title
        description:
          type: string
          description: Task description
        status:
          type: string
          enum: [active, completed, archived]
          description: Task status
        priority:
          type: string
          enum: [low, medium, high]
          description: Task priority
          default: medium
        due_date:
          type: string
          format: date-time
          description: Due date and time for the task
        reminder_time:
          type: string
          format: date-time
          description: Time to send reminder
        recurrence_pattern:
          type: object
          description: Recurrence pattern for recurring tasks
          properties:
            type:
              type: string
              enum: [daily, weekly, monthly]
            interval:
              type: integer
            end_date:
              type: string
              format: date-time
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the task
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        completed_at:
          type: string
          format: date-time
          description: Completion timestamp

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
          description: Task title
        description:
          type: string
          description: Task description
        priority:
          type: string
          enum: [low, medium, high]
          default: medium
        due_date:
          type: string
          format: date-time
          description: Due date and time for the task
        reminder_time:
          type: string
          format: date-time
          description: Time to send reminder
        recurrence_pattern:
          type: object
          description: Recurrence pattern for recurring tasks
          properties:
            type:
              type: string
              enum: [daily, weekly, monthly]
            interval:
              type: integer
            end_date:
              type: string
              format: date-time
        tags:
          type: array
          items:
            type: string
          description: Tags to associate with the task

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
          description: Task title
        description:
          type: string
          description: Task description
        status:
          type: string
          enum: [active, completed, archived]
          description: Task status
        priority:
          type: string
          enum: [low, medium, high]
          description: Task priority
        due_date:
          type: string
          format: date-time
          description: Due date and time for the task
        reminder_time:
          type: string
          format: date-time
          description: Time to send reminder
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the task

    Tag:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the tag
        name:
          type: string
          maxLength: 50
          description: Tag name
        color:
          type: string
          pattern: "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
          description: Color code for the tag

    TagCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 50
          description: Tag name
        color:
          type: string
          pattern: "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
          description: Color code for the tag

    Event:
      type: object
      required:
        - event_type
        - task_id
        - timestamp
      properties:
        event_type:
          type: string
          enum: [created, updated, completed, deleted, reminder]
          description: Type of event
        task_id:
          type: string
          format: uuid
          description: ID of the task this event relates to
        timestamp:
          type: string
          format: date-time
          description: When the event occurred
        payload:
          type: object
          description: Additional event-specific data

  responses:
    BadRequest:
      description: Bad request - validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
              details:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      description: Field with error
                    message:
                      type: string
                      description: Error message

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message