// frontend/chatkit/StreamChatUI.tsx
import React, { useState, useEffect } from 'react';
import { Channel, Chat, MessageList, MessageInput, ChannelHeader, ChannelList } from 'stream-chat-react';
import { StreamChat } from 'stream-chat';
import { streamConfig } from '../config/streamConfig';

interface StreamChatUIProps {
  userId: string;
}

const StreamChatUI: React.FC<StreamChatUIProps> = ({ userId }) => {
  const [chatClient, setChatClient] = useState<any>(null);
  const [configError, setConfigError] = useState<string | null>(null);
  const [todoChannel, setTodoChannel] = useState<any>(null);
  const [isConnected, setIsConnected] = useState<boolean>(false);

  useEffect(() => {
    // Check if API key is available before initializing Stream Chat client
    if (!streamConfig.apiKey || streamConfig.apiKey === 'YOUR_STREAM_API_KEY') {
      // In development, we can show a mock chat interface if API keys are not configured
      if (process.env.NODE_ENV === 'development') {
        console.warn('Stream Chat API key not configured, using mock chat interface for development');
        setChatClient({ isMock: true }); // Set a mock client for development
        return;
      } else {
        const errorMsg = 'Stream Chat API key is not configured. Please set NEXT_PUBLIC_STREAM_API_KEY in your environment variables.';
        console.error(errorMsg);
        setConfigError(errorMsg);
        return;
      }
    }

    // For development, we can proceed with just the API key and generate a temporary token
    if (!streamConfig.userToken || streamConfig.userToken === 'YOUR_USER_TOKEN') {
      if (process.env.NODE_ENV === 'development') {
        console.warn('Stream Chat user token not configured, this may cause issues in production');
        // We'll continue with the API key and let the connection fail gracefully if needed
      } else {
        const errorMsg = 'Stream Chat user token is not configured. Please set NEXT_PUBLIC_STREAM_USER_TOKEN in your environment variables.';
        console.error(errorMsg);
        setConfigError(errorMsg);
        return;
      }
    }

    setConfigError(null); // Clear any previous config errors

    // Initialize Stream Chat client with validation
    if (!streamConfig.apiKey) {
      const errorMsg = 'Stream Chat API key is not configured properly.';
      console.error(errorMsg);
      setConfigError(errorMsg);
      return;
    }

    const client = new StreamChat(streamConfig.apiKey);

    // Set user with token - the token must be specifically generated for the userId
    let token = streamConfig.userToken;
    if (!token || token === 'YOUR_USER_TOKEN') {
      // For development, we can generate an anonymous token or handle the error gracefully
      console.warn('User token not configured - in production, tokens must be generated server-side');

      // For development, we'll generate a temporary token using Stream's development token feature
      // This is only for development and should never be used in production
      if (process.env.NODE_ENV === 'development') {
        try {
          // Stream provides a development token generator for testing
          // This is only safe to use in development environments
          const devToken = client.devToken(userId);
          token = devToken;
          console.log('Generated development token for user:', userId);
        } catch (error) {
          console.error('Error generating development token:', error);
        }
      }
    }

    // Ensure the token is associated with the correct userId
    const setUserPromise = client.connectUser(
      {
        id: userId,
        name: `User ${userId}`,
        image: `https://getstream.io/random_svg/?name=User+${userId}`,
      },
      token // In production, this should be a proper JWT token generated by your backend for this specific user ID
    )
    .then(() => {
      // Connection successful
      setChatClient(client);

      // Wait for the client to be fully ready
      client.on('connection.changed', (event) => {
        if (event.online) {
          setIsConnected(true);
        }
      });

      // Create the channel after successful connection
      const channel = client.channel('messaging', 'todo-general', {
        name: 'Todo Discussion',
        members: [userId],
      });
      setTodoChannel(channel);

      // Set up message listener to handle AI processing
      client.on('message.new', async (event) => {
        if (event.message.user.id === userId) {
          // This is a message from the current user, send it to your AI backend
          try {
            const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
            const response = await fetch(`${API_BASE_URL}/api/${userId}/chat`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({ message: event.message.text }),
            });

            if (response.ok) {
              const data = await response.json();
              // Send the AI response back to the Stream channel
              await channel.sendMessage({
                text: data.response,
                user: {
                  id: 'ai-assistant',
                  name: 'Todo AI Assistant',
                  image: 'https://getstream.io/random_svg/?name=AI+Assistant',
                }
              });
            }
          } catch (error) {
            console.error('Error processing AI response:', error);
          }
        }
      });

      // Set connected state immediately after setting up everything
      setIsConnected(true);
    })
    .catch((error) => {
      console.error('Failed to connect user:', error);
      if (process.env.NODE_ENV === 'development') {
        console.warn('Development mode: connection failed. This could be due to:');
        console.warn('1. User token not matching the userId');
        console.warn('2. User token generated for a different user ID');
        console.warn('3. Invalid or expired token');
        console.warn('4. Missing or invalid API key');
        console.warn('Please ensure your user token was generated for userId:', userId);

        // For development, we can set a mock client to at least show the UI
        // But only after trying to use dev token
        if (!token || token === 'YOUR_USER_TOKEN') {
          // If we couldn't generate a dev token, use mock client
          setChatClient({ isMock: true });
        }
      } else {
        setConfigError('Failed to connect to chat service. Please check that your user token matches the user ID.');
      }
    });

    // Cleanup on unmount
    return () => {
      if (client && !client.isMock) {
        client.disconnectUser();
      }
      // Clean up channel state and connection state
      setTodoChannel(null);
      setIsConnected(false);
    };
  }, [userId]);

  if (configError) {
    return (
      <div style={{ padding: '20px', color: 'red', maxWidth: '600px' }}>
        <h3>Chat Configuration Error</h3>
        <p>{configError}</p>
        <p style={{ marginTop: '10px', fontSize: 'smaller', color: 'gray' }}>
          To fix this issue:
          <ol>
            <li>Get your Stream API key from the <a href="https://getstream.io/chat/dashboard/" target="_blank" rel="noopener noreferrer">Stream Dashboard</a></li>
            <li>Generate a user token for your user ID (instructions in the console)</li>
            <li>Create or update your <code>.env.local</code> file in the frontend directory with:
              <pre style={{ backgroundColor: '#f5f5f5', padding: '10px', margin: '10px 0' }}>
                {`NEXT_PUBLIC_STREAM_API_KEY=your_api_key_here
NEXT_PUBLIC_STREAM_USER_TOKEN=your_user_token_here`}
              </pre>
            </li>
          </ol>
          <p style={{ fontSize: 'smaller', marginTop: '10px' }}>
            <strong>Note:</strong> User tokens should be generated server-side in production. For development, you can generate one in the Stream dashboard.
          </p>
        </p>
      </div>
    );
  }

  if (!chatClient) {
    return <div>Loading chat...</div>;
  }

  // Handle mock client for development
  if (chatClient.isMock) {
    // For development without API keys, show a placeholder
    return (
      <div style={{ padding: '20px', maxWidth: '800px', margin: '0 auto' }}>
        <h3>Stream Chat UI (Development Mode)</h3>
        <p>Stream Chat is not configured. To use the chat feature:</p>
        <ol>
          <li>Create a <code>.env.local</code> file in the frontend directory</li>
          <li>Add your Stream API key and user token:</li>
        </ol>
        <pre style={{ backgroundColor: '#f5f5f5', padding: '10px', margin: '10px 0' }}>
          {`NEXT_PUBLIC_STREAM_API_KEY=your_api_key_here
NEXT_PUBLIC_STREAM_USER_TOKEN=your_user_token_here`}
        </pre>
        <p>Chat functionality will be available once properly configured.</p>
      </div>
    );
  }

  // Only render the chat interface after both client and channel are ready
  if (!chatClient || chatClient.isMock || !todoChannel || !isConnected) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
        <div>Loading chat...</div>
      </div>
    );
  }

  return (
    <Chat client={chatClient} theme="str-chat__theme-dark">
      <div style={{ display: 'flex', height: '100vh', width: '100%' }}>
        <div style={{ width: '300px' }}>
          <ChannelList
            filters={{ type: 'messaging' }}
            options={{ state: true, presence: true }}
          />
        </div>
        <div style={{ width: '100%' }}>
          <Channel channel={todoChannel}>
            <ChannelHeader />
            <MessageList />
            <MessageInput />
          </Channel>
        </div>
      </div>
    </Chat>
  );
};

export default StreamChatUI;