"""Add series_id to tasks and create task_series table

Revision ID: 002_add_series_to_tasks
Revises: 001_add_recurring_task_features
Create Date: 2026-02-17 17:08:28.445882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid

from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '002_add_series_to_tasks'
down_revision: Union[str, None] = '001_add_recurring_task_features'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_series',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('user_id', sa.VARCHAR(), nullable=False),
        sa.Column('recurrence_pattern', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('series_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'series_id')
    op.drop_table('task_series')
    # ### end Alembic commands ###