#!/bin/bash

# Script to check Gordon (Docker AI Agent) availability and provide Docker CLI alternatives

echo "🔍 Checking Gordon (Docker AI Agent) availability..."

# Check if Docker is available
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed or not in PATH"
    exit 1
fi

echo "✅ Docker is installed"

# Test Gordon availability
echo "🧪 Testing Gordon (Docker AI Agent) availability..."
if docker ai "ping" &> /dev/null; then
    echo "✅ Gordon (Docker AI Agent) is AVAILABLE in your region!"
    echo "You can use Gordon for intelligent Docker operations:"
    echo ""
    echo "Examples:"
    echo "  docker ai \"optimize the Dockerfile for smaller image size\""
    echo "  docker ai \"suggest security improvements for the container\""
    echo "  docker ai \"explain what this Dockerfile does\""
    echo "  docker ai \"create a multi-stage Dockerfile for this project\""
    echo ""
    echo "Gordon is available and ready to assist with:"
    echo "  • Dockerfile optimization"
    echo "  • Security improvements"
    echo "  • Multi-stage builds"
    echo "  • Performance tuning"
    echo "  • Troubleshooting"
else
    echo "❌ Gordon (Docker AI Agent) is NOT AVAILABLE in your region or tier"
    echo ""
    echo "🔄 FALLING BACK TO STANDARD DOCKER CLI COMMANDS"
    echo ""
    echo "Here are the standard Docker commands for the Todo Chatbot:"
    echo ""
    echo "# Build all services:"
    echo "docker build -t todo-chatbot-backend:latest ./backend"
    echo "docker build -t todo-chatbot-frontend:latest ./frontend"
    echo "docker build -t todo-chatbot-mcp-server:latest ./mcp_server"
    echo ""
    echo "# Run individual services:"
    echo "docker run -d --name todo-backend -p 8000:8000 \\"
    echo "  -e DATABASE_URL=postgresql://localhost:5432/todo_db \\"
    echo "  -e OPENAI_API_KEY=\$OPENAI_API_KEY \\"
    echo "  -e SECRET_KEY=\$SECRET_KEY \\"
    echo "  todo-chatbot-backend:latest"
    echo ""
    echo "docker run -d --name todo-frontend -p 3000:80 \\"
    echo "  --link todo-backend \\"
    echo "  todo-chatbot-frontend:latest"
    echo ""
    echo "docker run -d --name todo-mcp-server -p 8001:8001 \\"
    echo "  -e DATABASE_URL=postgresql://localhost:5432/todo_db \\"
    echo "  -e OPENAI_API_KEY=\$OPENAI_API_KEY \\"
    echo "  todo-chatbot-mcp-server:latest"
    echo ""
    echo "# Or use docker-compose for orchestrated deployment:"
    echo "docker-compose up -d --build"
    echo ""
    echo "# Docker CLI alternatives for common operations:"
    echo ""
    echo "# Build with specific platform:"
    echo "docker build --platform linux/amd64 -t todo-chatbot-backend:latest ./backend"
    echo ""
    echo "# Multi-stage build (if applicable):"
    echo "docker build --target production -t todo-chatbot-backend:latest ./backend"
    echo ""
    echo "# Build with build arguments:"
    echo "docker build --build-arg NODE_ENV=production -t todo-chatbot-frontend:latest ./frontend"
    echo ""
    echo "# Run with resource limits:"
    echo "docker run -d --name todo-backend \\"
    echo "  --memory=512m --cpus=1.0 \\"
    echo "  -p 8000:8000 \\"
    echo "  todo-chatbot-backend:latest"
    echo ""
    echo "# Run with volume mounts:"
    echo "docker run -d --name todo-backend \\"
    echo "  -v todo-data:/app/data \\"
    echo "  -p 8000:8000 \\"
    echo "  todo-chatbot-backend:latest"
    echo ""
    echo "# Docker network setup:"
    echo "docker network create todo-network"
    echo "docker run -d --name postgres --network todo-network \\"
    echo "  -e POSTGRES_DB=todo_db \\"
    echo "  -e POSTGRES_USER=postgres \\"
    echo "  -e POSTGRES_PASSWORD=postgres \\"
    echo "  postgres:15"
    echo ""
    echo "# Multi-container orchestration:"
    echo "docker run -d --name todo-backend --network todo-network \\"
    echo "  -e DATABASE_URL=postgresql://postgres:5432/todo_db \\"
    echo "  todo-chatbot-backend:latest"
    echo ""
    echo "docker run -d --name todo-frontend --network todo-network \\"
    echo "  -p 3000:80 \\"
    echo "  todo-chatbot-frontend:latest"
    echo ""
    echo "# Docker image optimization commands:"
    echo "docker images | grep todo-chatbot  # List all todo-chatbot images"
    echo "docker image prune  # Remove unused images"
    echo "docker build --no-cache -t todo-chatbot-backend:latest ./backend  # Clean build"
    echo "docker history todo-chatbot-backend:latest  # Show image layers"
    echo ""
    echo "📝 TIP: Use the docker-compose.yml file in this directory for easier multi-service management!"
fi